/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/users/{userID}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a user by id
     * @description Retrieves a user with detailed metadata by the provided id
     */
    get: operations['getV1UsersByUserID'];
    /**
     * Update a current user
     * @description Update the user with the provided id, if they have permissions to do so
     */
    put: operations['putV1UsersByUserID'];
    post?: never;
    /**
     * Delete a user
     * @description Delete the user with the provided id, if they have permissions to do so
     */
    delete: operations['deleteV1UsersByUserID'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /v1/health */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: never;
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all users
     * @description Get a paginated list of users, minus any hidden users
     */
    get: operations['getV1Users'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PageUserSummaryResponseDTO: {
      metadata: components['schemas']['PageMetadata'];
      items: components['schemas']['UserSummaryResponseDTO'][];
    };
    PageMetadata: {
      /** Format: int64 */
      page: number;
      /** Format: int64 */
      per: number;
      /** Format: int64 */
      total: number;
    };
    UserSummaryResponseDTO: {
      email: string;
      firstName: string;
      /** Format: date-time */
      updatedAt: string;
      lastName: string;
      membershipLevel?: components['schemas']['MembershipLevelDTO'];
      /** Format: date-time */
      createdAt: string;
      hasOrientation: boolean;
      /** Format: uuid */
      id: string;
    };
    RoleDTO: {
      name: string;
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserDetailedResponseDTO: {
      githubUrl?: string | null;
      marketingSource?: string | null;
      emergencyName?: string | null;
      desiredSkills?: string | null;
      lastName: string;
      emergencyPhone?: string | null;
      instructorStations: components['schemas']['StationBasicDTO'][];
      firstName: string;
      email: string;
      paymentMethod?: string | null;
      /** Format: uuid */
      id: string;
      membershipLevel?: components['schemas']['MembershipLevelDTO'];
      emailVisible?: boolean | null;
      /** Format: date-time */
      createdAt: string;
      phoneVisible?: boolean | null;
      roles: components['schemas']['RoleDTO'][];
      /** Format: date-time */
      waiver?: string | null;
      emergencyEmail?: string | null;
      phone?: string | null;
      postalCode?: string | null;
      facebookUrl?: string | null;
      twitterUrl?: string | null;
      orientation?: components['schemas']['OrientationDTO'];
      websiteUrl?: string | null;
      currentSkills?: string | null;
      /** Format: date-time */
      updatedAt: string;
      exitReason?: string | null;
    };
    UserRequestDTO: {
      phone?: string | null;
      firstName: string;
      exitReason?: string | null;
      /** Format: date-time */
      waiverSignedOn?: string | null;
      emergencyEmail?: string | null;
      currentSkills?: string | null;
      emailVisible: boolean;
      twitterURL?: string | null;
      phoneVisible: boolean;
      lastName: string;
      marketingSource?: string | null;
      githubURL?: string | null;
      websiteURL?: string | null;
      emergencyName?: string | null;
      facebookURL?: string | null;
      email: string;
      desiredSkills?: string | null;
      paymentMethod?: string | null;
      emergencyPhone?: string | null;
      postalCode?: string | null;
    };
    StationBasicDTO: {
      name: string;
      /** Format: uuid */
      id: string;
    };
    MembershipLevelDTO: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: int64 */
      costInCents: number;
    };
    OrientationDTO: {
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      orientedById: string;
      /** Format: date-time */
      createdAt: string;
      orientedByName: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getV1UsersByUserID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDetailedResponseDTO'];
        };
      };
    };
  };
  putV1UsersByUserID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserRequestDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserDetailedResponseDTO'];
        };
      };
    };
  };
  deleteV1UsersByUserID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userID: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  getV1Users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PageUserSummaryResponseDTO'];
        };
      };
    };
  };
}
