name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: |
          cd clients
          pnpm install
      - name: Run Prettier
        run: |
          cd clients
          pnpm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: |
          cd clients
          pnpm install
      - name: Run TypeScript
        run: |
          cd clients
          pnpm run typecheck:client
